CREATE TABLE trac_nghiem (
    stt int , 
    dap_an varchar(150)   
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

insert into trac_nghiem(stt,dap_an) values (1, 'C. Service');
insert into trac_nghiem(stt,dap_an) values (2, 'B. LinearLayout');
insert into trac_nghiem(stt,dap_an) values (3, 'C. Khởi chạy Activity');
insert into trac_nghiem(stt,dap_an) values (4, 'C. onCreate');
insert into trac_nghiem(stt,dap_an) values (5, 'A. onClick');
insert into trac_nghiem(stt,dap_an) values (6, 'D. boolean');
insert into trac_nghiem(stt,dap_an) values (7, 'C. Lưu trữ dữ liệu dạng key-value');
insert into trac_nghiem(stt,dap_an) values (8, 'B. Hiển thị một thông báo ngắn gọn cho người dùng');
insert into trac_nghiem(stt,dap_an) values (9, 'C. Java,D. Kotlin');
insert into trac_nghiem(stt,dap_an) values (10, 'A. Kết nối dữ liệu với ListView hoặc RecyclerView');
insert into trac_nghiem(stt,dap_an) values (11, 'B. Một thành phần UI có thể tái sử dụng');
insert into trac_nghiem(stt,dap_an) values (12, 'A. Một thành phần UI để hiển thị danh sách');
insert into trac_nghiem(stt,dap_an) values (13, 'A. Khai báo các thành phần của ứng dụng');
insert into trac_nghiem(stt,dap_an) values (14, 'A. Một công cụ để quản lý dependencies');
insert into trac_nghiem(stt,dap_an) values (15, 'A. Xử lý các tác vụ chạy nền');
insert into trac_nghiem(stt,dap_an) values (16, 'A. Chia sẻ dữ liệu giữa các ứng dụng');
insert into trac_nghiem(stt,dap_an) values (17, 'A. Một hệ quản trị cơ sở dữ liệu');
insert into trac_nghiem(stt,dap_an) values (18, 'A. Nhận các thông báo từ hệ thống');
insert into trac_nghiem(stt,dap_an) values (19, 'A. Một thành phần ứng dụng chạy nền');
insert into trac_nghiem(stt,dap_an) values (20, 'A. Một luồng xử lý');
insert into trac_nghiem(stt,dap_an) values (21, 'A. Quá trình tạo, khởi động, tạm dừng và hủy một Activity');
insert into trac_nghiem(stt,dap_an) values (22, 'A. Tạo các đối tượng View từ file XML');
insert into trac_nghiem(stt,dap_an) values (23, 'A. Một tài nguyên đồ họa');
insert into trac_nghiem(stt,dap_an) values (24, 'A. Đơn vị đo lường độc lập với mật độ điểm ảnh');
insert into trac_nghiem(stt,dap_an) values (25, 'C. Color,D. Hexadecimal');
insert into trac_nghiem(stt,dap_an) values (26, 'A. Một lớp cơ sở cho tất cả các layout');
insert into trac_nghiem(stt,dap_an) values (27, 'B. Thành phần UI sẽ có chiều rộng bằng với chiều rộng của thành phần cha');
insert into trac_nghiem(stt,dap_an) values (28, 'A. Căn chỉnh nội dung của một thành phần UI');
insert into trac_nghiem(stt,dap_an) values (29, 'C. Thư mục gốc của project');
insert into trac_nghiem(stt,dap_an) values (30, 'A. Kết nối thiết bị với máy tính và bật chế độ USB debugging');
insert into trac_nghiem(stt,dap_an) values (31, 'A. dp là đơn vị đo lường độc lập với mật độ điểm ảnh, sp là đơn vị đo lường phụ thuộc vào mật độ điểm ảnh');
insert into trac_nghiem(stt,dap_an) values (32, 'A. Hiển thị một hộp thoại cho người dùng');
insert into trac_nghiem(stt,dap_an) values (33, 'B. Khai báo các Activity có thể xử lý một Intent');
insert into trac_nghiem(stt,dap_an) values (34, 'A. Một interface để lưu trữ đối tượng vào bộ nhớ');
insert into trac_nghiem(stt,dap_an) values (35, ' D. Cả A, B và C');
insert into trac_nghiem(stt,dap_an) values (36, 'A. Tối ưu hóa hiệu năng của ListView và RecyclerView');
insert into trac_nghiem(stt,dap_an) values (37, 'A. Một kỹ thuật để kết nối dữ liệu với giao diện người dùng');
insert into trac_nghiem(stt,dap_an) values (38, 'A. Một kiến trúc phần mềm');
insert into trac_nghiem(stt,dap_an) values (39, 'A. Một thư viện để thực hiện các request HTTP');
insert into trac_nghiem(stt,dap_an) values (40, 'A. Một thư viện để chuyển đổi giữa JSON và Java object');
insert into trac_nghiem(stt,dap_an) values (41, 'A. Một thư viện để tải và hiển thị hình ảnh');
insert into trac_nghiem(stt,dap_an) values (42, 'A. Một nền tảng di động của Google');
insert into trac_nghiem(stt,dap_an) values (43, 'A. Một layout linh hoạt để sắp xếp các thành phần UI');
insert into trac_nghiem(stt,dap_an) values (44, 'B. Trong file Java/Kotlin');
insert into trac_nghiem(stt,dap_an) values (45, 'A. Lưu trữ và quản lý dữ liệu cho UI');
insert into trac_nghiem(stt,dap_an) values (46, 'A. Một lớp để giữ và quan sát dữ liệu');
insert into trac_nghiem(stt,dap_an) values (47, 'A. Một thư viện để làm việc với cơ sở dữ liệu SQLite');
insert into trac_nghiem(stt,dap_an) values (48, 'A. Một toolkit để xây dựng giao diện người dùng theo hướng khai báo');
insert into trac_nghiem(stt,dap_an) values (49, 'B. ListView,D. RecyclerView');
insert into trac_nghiem(stt,dap_an) values (50, 'A. Intent có thể được sử dụng để truyền dữ liệu giữa các Activity,C. Intent có thể được sử dụng để khởi chạy Service');
insert into trac_nghiem(stt,dap_an) values (51, 'A. onCreate(),C. onStart(),D. onResume(),E. onDestroy()');
insert into trac_nghiem(stt,dap_an) values (52, 'A. Retrofit,B. Gson,C. Picasso');
insert into trac_nghiem(stt,dap_an) values (53, 'A. Giúp giảm thiểu việc lồng ghép layout,B. Cải thiện hiệu năng của ứng dụng');
insert into trac_nghiem(stt,dap_an) values (54, 'A. Model,B. View,D. ViewModel');
insert into trac_nghiem(stt,dap_an) values (55, 'A. Android Studio Debugger,B. Logcat,C. ADB');
insert into trac_nghiem(stt,dap_an) values (56, 'A. Sử dụng ViewHolder pattern,B. Sử dụng AsyncTask cho các tác vụ chạy nền,C. Giảm thiểu việc sử dụng bộ nhớ,D. Tối ưu hóa hình ảnh');
insert into trac_nghiem(stt,dap_an) values (57, 'A. SharedPreferences,B. SQLite,C. ContentProvider');